Google play store

In [1]:
pip install pandas matplotlib seaborn

Requirement already satisfied: pandas in ./venv/lib/python3.13/site-packages (2.2.3)
Requirement already satisfied: matplotlib in ./venv/lib/python3.13/site-packages (3.10.1)
Requirement already satisfied: seaborn in ./venv/lib/python3.13/site-packages (0.13.2)
Requirement already satisfied: numpy>=1.26.0 in ./venv/lib/python3.13/site-packages (from pandas) (2.2.3)
Requirement already satisfied: python-dateutil>=2.8.2 in ./venv/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in ./venv/lib/python3.13/site-packages (from pandas) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in ./venv/lib/python3.13/site-packages (from pandas) (2025.1)
Requirement already satisfied: contourpy>=1.0.1 in ./venv/lib/python3.13/site-packages (from matplotlib) (1.3.1)
Requirement already satisfied: cycler>=0.10 in ./venv/lib/python3.13/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in ./venv/lib/python3.13/site-packages (from matplotlib) (4.56.0)
Requirement already satisfied: kiwisolver>=1.3.1 in ./venv/lib/python3.13/site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: packaging>=20.0 in ./venv/lib/python3.13/site-packages (from matplotlib) (24.2)
Requirement already satisfied: pillow>=8 in ./venv/lib/python3.13/site-packages (from matplotlib) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in ./venv/lib/python3.13/site-packages (from matplotlib) (3.2.1)
Requirement already satisfied: six>=1.5 in ./venv/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.0 -> 25.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
data = pd.read_csv("googleplaystore.csv")

Prétraitement et exploration de données

In [4]:
data.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [5]:
data.shape

(10841, 13)

Le jeux de données contient 10841 lignes et 13 colonnes. Chaque ligne correspond à une application de google play store, et chaque colonne correspond à une caractéristique sur cette application. Les caractéristiques sont les suivantes :

App : nom de l'application 
Category : catégorie de l'application 
Rating : note moyenne donnée par les utilisateurs (entre 0 et 5) 
Review : nombre d'avis laissés par les utilisateurs
Size : taille de l'application 
Installs : nombre d'installation 
Type : app gratuite ou payante 
Price : prix de l'app 
Content rating : public cible 
Genres : genres de l'application 
Last Updates : dernière mise à jour de l'app
Current ver : version actuelle de l'app

Suppresion des colonnes inutiles

In [6]:
data = data.drop(["Current Ver","Android Ver",  "Genres"], axis=1)

In [7]:
data.head(3)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Last Updated
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,"January 7, 2018"
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,"January 15, 2018"
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,"August 1, 2018"

In [8]:
print("Nombre de lignes dupliquées :", data.duplicated().sum())

Nombre de lignes dupliquées : 483

In [9]:
dupes = data[data.duplicated(keep=False)]
print(dupes)

                                                   App             Category  \
164                                       Ebook Reader  BOOKS_AND_REFERENCE
192                      Docs To Go™ Free Office Suite             BUSINESS
193                                 Google My Business             BUSINESS
204                                                Box             BUSINESS
213                                ZOOM Cloud Meetings             BUSINESS
...                                                ...                  ...
8643                    Wunderlist: To-Do List & Tasks         PRODUCTIVITY
8654   TickTick: To Do List with Reminder, Day Planner         PRODUCTIVITY
8658                           ColorNote Notepad Notes         PRODUCTIVITY
10049        Airway Ex - Intubate. Anesthetize. Train.              MEDICAL
10768                                             AAFP              MEDICAL

       Rating  Reviews                Size      Installs  Type Price  \
164       4.1    85842                 37M    5,000,000+  Free     0
192       4.1   217730  Varies with device   50,000,000+  Free     0
193       4.4    70991  Varies with device    5,000,000+  Free     0
204       4.2   159872  Varies with device   10,000,000+  Free     0
213       4.4    31614                 37M   10,000,000+  Free     0
...       ...      ...                 ...           ...   ...   ...
8643      4.6   404610  Varies with device   10,000,000+  Free     0
8654      4.6    25370  Varies with device    1,000,000+  Free     0
8658      4.6  2401017  Varies with device  100,000,000+  Free     0
10049     4.3      123                 86M       10,000+  Free     0
10768     3.8       63                 24M       10,000+  Free     0

      Content Rating    Last Updated
164         Everyone   June 25, 2018
192         Everyone   April 2, 2018
193         Everyone   July 24, 2018
204         Everyone   July 31, 2018
213         Everyone   July 20, 2018
...              ...             ...
8643        Everyone   April 6, 2018
8654        Everyone  August 6, 2018
8658        Everyone   June 27, 2018
10049       Everyone    June 1, 2018
10768       Everyone   June 22, 2018

[893 rows x 10 columns]

In [10]:
#Supprimer les lignes duppliquées : 
data = data.drop_duplicates(keep='first') 
#print(data_cleaned)

In [11]:
print("Nombre de lignes dupliquées :", data.duplicated().sum())

Nombre de lignes dupliquées : 0

In [12]:
data.shape

(10358, 10)

In [13]:
categories = data['Category'].unique()
print(categories)

['ART_AND_DESIGN' 'AUTO_AND_VEHICLES' 'BEAUTY' 'BOOKS_AND_REFERENCE'
 'BUSINESS' 'COMICS' 'COMMUNICATION' 'DATING' 'EDUCATION' 'ENTERTAINMENT'
 'EVENTS' 'FINANCE' 'FOOD_AND_DRINK' 'HEALTH_AND_FITNESS' 'HOUSE_AND_HOME'
 'LIBRARIES_AND_DEMO' 'LIFESTYLE' 'GAME' 'FAMILY' 'MEDICAL' 'SOCIAL'
 'SHOPPING' 'PHOTOGRAPHY' 'SPORTS' 'TRAVEL_AND_LOCAL' 'TOOLS'
 'PERSONALIZATION' 'PRODUCTIVITY' 'PARENTING' 'WEATHER' 'VIDEO_PLAYERS'
 'NEWS_AND_MAGAZINES' 'MAPS_AND_NAVIGATION' '1.9']

In [14]:
moyenne_rating_par_categorie = data.groupby("Category")["Rating"].mean()
moyenne_rating_par_categorie = moyenne_rating_par_categorie.sort_values(ascending=False)
print(moyenne_rating_par_categorie)

Category
1.9                    19.000000
EVENTS                  4.435556
EDUCATION               4.375969
ART_AND_DESIGN          4.358065
BOOKS_AND_REFERENCE     4.347458
PERSONALIZATION         4.333871
PARENTING               4.300000
GAME                    4.281285
BEAUTY                  4.278571
HEALTH_AND_FITNESS      4.261450
SOCIAL                  4.254918
SHOPPING                4.251485
WEATHER                 4.244000
SPORTS                  4.225175
PRODUCTIVITY            4.201796
FAMILY                  4.191153
AUTO_AND_VEHICLES       4.190411
PHOTOGRAPHY             4.182895
MEDICAL                 4.182450
LIBRARIES_AND_DEMO      4.178462
HOUSE_AND_HOME          4.164706
FOOD_AND_DRINK          4.164151
COMICS                  4.155172
COMMUNICATION           4.151466
ENTERTAINMENT           4.136036
NEWS_AND_MAGAZINES      4.128505
FINANCE                 4.127445
BUSINESS                4.102593
LIFESTYLE               4.096066
TRAVEL_AND_LOCAL        4.094146
VIDEO_PLAYERS           4.063750
MAPS_AND_NAVIGATION     4.051613
TOOLS                   4.047411
DATING                  3.971698
Name: Rating, dtype: float64

C'est quoi la catégorie 1.9 ?

In [15]:
print(data[data["Category"] == "1.9"])

                                           App Category  Rating Reviews  \
10472  Life Made WI-Fi Touchscreen Photo Frame      1.9    19.0    3.0M

         Size Installs Type     Price Content Rating Last Updated
10472  1,000+     Free    0  Everyone            NaN       1.0.19

In [16]:
#Il y a un décalage dans les données 
print(data.loc[10472])

App               Life Made WI-Fi Touchscreen Photo Frame
Category                                              1.9
Rating                                               19.0
Reviews                                              3.0M
Size                                               1,000+
Installs                                             Free
Type                                                    0
Price                                            Everyone
Content Rating                                        NaN
Last Updated                                       1.0.19
Name: 10472, dtype: object

On supprime cette ligne :

In [17]:
data = data.drop(10472)

In [18]:
stats_category = data["Category"].describe()
print(stats_category)

count      10357
unique        33
top       FAMILY
freq        1943
Name: Category, dtype: object

In [19]:
print(data.isnull().sum())

App                  0
Category             0
Rating            1465
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       0
Last Updated         0
dtype: int64

In [20]:
print(data["Price"].unique())

['0' '$4.99' '$3.99' '$6.99' '$1.49' '$2.99' '$7.99' '$5.99' '$3.49'
 '$1.99' '$9.99' '$7.49' '$0.99' '$9.00' '$5.49' '$10.00' '$24.99'
 '$11.99' '$79.99' '$16.99' '$14.99' '$1.00' '$29.99' '$12.99' '$2.49'
 '$10.99' '$1.50' '$19.99' '$15.99' '$33.99' '$74.99' '$39.99' '$3.95'
 '$4.49' '$1.70' '$8.99' '$2.00' '$3.88' '$25.99' '$399.99' '$17.99'
 '$400.00' '$3.02' '$1.76' '$4.84' '$4.77' '$1.61' '$2.50' '$1.59' '$6.49'
 '$1.29' '$5.00' '$13.99' '$299.99' '$379.99' '$37.99' '$18.99' '$389.99'
 '$19.90' '$8.49' '$1.75' '$14.00' '$4.85' '$46.99' '$109.99' '$154.99'
 '$3.08' '$2.59' '$4.80' '$1.96' '$19.40' '$3.90' '$4.59' '$15.46' '$3.04'
 '$4.29' '$2.60' '$3.28' '$4.60' '$28.99' '$2.95' '$2.90' '$1.97'
 '$200.00' '$89.99' '$2.56' '$30.99' '$3.61' '$394.99' '$1.26' '$1.20'
 '$1.04']

In [21]:
nb_apps_free = len(data[data["Price"]==0])
print (nb_apps_free )

0

Les prix sont sous forme de chaine de caractère, convertissons les en nombre

In [22]:
data["Price"] = data["Price"].astype(str).replace({'\$': '', ',': ''}, regex=True)

data["Price"] = data["Price"].astype(float)

print(data["Price"].unique())

[  0.     4.99   3.99   6.99   1.49   2.99   7.99   5.99   3.49   1.99
   9.99   7.49   0.99   9.     5.49  10.    24.99  11.99  79.99  16.99
  14.99   1.    29.99  12.99   2.49  10.99   1.5   19.99  15.99  33.99
  74.99  39.99   3.95   4.49   1.7    8.99   2.     3.88  25.99 399.99
  17.99 400.     3.02   1.76   4.84   4.77   1.61   2.5    1.59   6.49
   1.29   5.    13.99 299.99 379.99  37.99  18.99 389.99  19.9    8.49
   1.75  14.     4.85  46.99 109.99 154.99   3.08   2.59   4.8    1.96
  19.4    3.9    4.59  15.46   3.04   4.29   2.6    3.28   4.6   28.99
   2.95   2.9    1.97 200.    89.99   2.56  30.99   3.61 394.99   1.26
   1.2    1.04]

<>:1: SyntaxWarning: invalid escape sequence '\$'
<>:1: SyntaxWarning: invalid escape sequence '\$'
/var/folders/kj/cf4lkqr54pb_nq_6f472s9400000gn/T/ipykernel_9969/3134949566.py:1: SyntaxWarning: invalid escape sequence '\$'
  data["Price"] = data["Price"].astype(str).replace({'\$': '', ',': ''}, regex=True)

In [23]:
nb_apps_free = len(data[data["Price"]==0])
print ("Nombre applications gratuites : ", nb_apps_free )

nb_apps_not_free = len(data[data["Price"]!=0])
print ("Nombre applications payantes : ",nb_apps_not_free )

Nombre applications gratuites :  9592
Nombre applications payantes :  765

In [24]:
print(data["Price"].unique())

[  0.     4.99   3.99   6.99   1.49   2.99   7.99   5.99   3.49   1.99
   9.99   7.49   0.99   9.     5.49  10.    24.99  11.99  79.99  16.99
  14.99   1.    29.99  12.99   2.49  10.99   1.5   19.99  15.99  33.99
  74.99  39.99   3.95   4.49   1.7    8.99   2.     3.88  25.99 399.99
  17.99 400.     3.02   1.76   4.84   4.77   1.61   2.5    1.59   6.49
   1.29   5.    13.99 299.99 379.99  37.99  18.99 389.99  19.9    8.49
   1.75  14.     4.85  46.99 109.99 154.99   3.08   2.59   4.8    1.96
  19.4    3.9    4.59  15.46   3.04   4.29   2.6    3.28   4.6   28.99
   2.95   2.9    1.97 200.    89.99   2.56  30.99   3.61 394.99   1.26
   1.2    1.04]

In [25]:
stats_price = data["Price"].describe()
print(stats_price)

count    10357.000000
mean         1.030800
std         16.278625
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max        400.000000
Name: Price, dtype: float64

In [26]:
print(data["Size"].unique())

['19M' '14M' '8.7M' '25M' '2.8M' '5.6M' '29M' '33M' '3.1M' '28M' '12M'
 '20M' '21M' '37M' '2.7M' '5.5M' '17M' '39M' '31M' '4.2M' '7.0M' '23M'
 '6.0M' '6.1M' '4.6M' '9.2M' '5.2M' '11M' '24M' 'Varies with device'
 '9.4M' '15M' '10M' '1.2M' '26M' '8.0M' '7.9M' '56M' '57M' '35M' '54M'
 '201k' '3.6M' '5.7M' '8.6M' '2.4M' '27M' '2.5M' '16M' '3.4M' '8.9M'
 '3.9M' '2.9M' '38M' '32M' '5.4M' '18M' '1.1M' '2.2M' '4.5M' '9.8M' '52M'
 '9.0M' '6.7M' '30M' '2.6M' '7.1M' '3.7M' '22M' '7.4M' '6.4M' '3.2M'
 '8.2M' '9.9M' '4.9M' '9.5M' '5.0M' '5.9M' '13M' '73M' '6.8M' '3.5M'
 '4.0M' '2.3M' '7.2M' '2.1M' '42M' '7.3M' '9.1M' '55M' '23k' '6.5M' '1.5M'
 '7.5M' '51M' '41M' '48M' '8.5M' '46M' '8.3M' '4.3M' '4.7M' '3.3M' '40M'
 '7.8M' '8.8M' '6.6M' '5.1M' '61M' '66M' '79k' '8.4M' '118k' '44M' '695k'
 '1.6M' '6.2M' '18k' '53M' '1.4M' '3.0M' '5.8M' '3.8M' '9.6M' '45M' '63M'
 '49M' '77M' '4.4M' '4.8M' '70M' '6.9M' '9.3M' '10.0M' '8.1M' '36M' '84M'
 '97M' '2.0M' '1.9M' '1.8M' '5.3M' '47M' '556k' '526k' '76M' '7.6M' '59M'
 '9.7M' '78M' '72M' '43M' '7.7M' '6.3M' '334k' '34M' '93M' '65M' '79M'
 '100M' '58M' '50M' '68M' '64M' '67M' '60M' '94M' '232k' '99M' '624k'
 '95M' '8.5k' '41k' '292k' '11k' '80M' '1.7M' '74M' '62M' '69M' '75M'
 '98M' '85M' '82M' '96M' '87M' '71M' '86M' '91M' '81M' '92M' '83M' '88M'
 '704k' '862k' '899k' '378k' '266k' '375k' '1.3M' '975k' '980k' '4.1M'
 '89M' '696k' '544k' '525k' '920k' '779k' '853k' '720k' '713k' '772k'
 '318k' '58k' '241k' '196k' '857k' '51k' '953k' '865k' '251k' '930k'
 '540k' '313k' '746k' '203k' '26k' '314k' '239k' '371k' '220k' '730k'
 '756k' '91k' '293k' '17k' '74k' '14k' '317k' '78k' '924k' '902k' '818k'
 '81k' '939k' '169k' '45k' '475k' '965k' '90M' '545k' '61k' '283k' '655k'
 '714k' '93k' '872k' '121k' '322k' '1.0M' '976k' '172k' '238k' '549k'
 '206k' '954k' '444k' '717k' '210k' '609k' '308k' '705k' '306k' '904k'
 '473k' '175k' '350k' '383k' '454k' '421k' '70k' '812k' '442k' '842k'
 '417k' '412k' '459k' '478k' '335k' '782k' '721k' '430k' '429k' '192k'
 '200k' '460k' '728k' '496k' '816k' '414k' '506k' '887k' '613k' '243k'
 '569k' '778k' '683k' '592k' '319k' '186k' '840k' '647k' '191k' '373k'
 '437k' '598k' '716k' '585k' '982k' '222k' '219k' '55k' '948k' '323k'
 '691k' '511k' '951k' '963k' '25k' '554k' '351k' '27k' '82k' '208k' '913k'
 '514k' '551k' '29k' '103k' '898k' '743k' '116k' '153k' '209k' '353k'
 '499k' '173k' '597k' '809k' '122k' '411k' '400k' '801k' '787k' '237k'
 '50k' '643k' '986k' '97k' '516k' '837k' '780k' '961k' '269k' '20k' '498k'
 '600k' '749k' '642k' '881k' '72k' '656k' '601k' '221k' '228k' '108k'
 '940k' '176k' '33k' '663k' '34k' '942k' '259k' '164k' '458k' '245k'
 '629k' '28k' '288k' '775k' '785k' '636k' '916k' '994k' '309k' '485k'
 '914k' '903k' '608k' '500k' '54k' '562k' '847k' '957k' '688k' '811k'
 '270k' '48k' '329k' '523k' '921k' '874k' '981k' '784k' '280k' '24k'
 '518k' '754k' '892k' '154k' '860k' '364k' '387k' '626k' '161k' '879k'
 '39k' '970k' '170k' '141k' '160k' '144k' '143k' '190k' '376k' '193k'
 '246k' '73k' '658k' '992k' '253k' '420k' '404k' '470k' '226k' '240k'
 '89k' '234k' '257k' '861k' '467k' '157k' '44k' '676k' '67k' '552k' '885k'
 '1020k' '582k' '619k']

In [27]:
print("Taille qui dépend de l'appareil utilisé : ",len(data[data["Size"]=='Varies with device']))
print("Taille qui ne dépend pas de l'appareil utilisé : ",len(data[data["Size"]!="Varies with device"]))

Taille qui dépend de l'appareil utilisé :  1526
Taille qui ne dépend pas de l'appareil utilisé :  8831

Il faut convertir la taille dans la même unité en k

In [28]:
def convert_size(size_str):
    if size_str == "Varies with device":
        return None
        
    elif size_str.endswith("M"):
        try:
            number = float(size_str[:-1])
            return number * 1000
        except ValueError:
            return size_str
   
    elif size_str.endswith("k"):
        try:
            return float(size_str[:-1])
        except ValueError:
            return size_str

    else:
        return size_str

data["Size"] = data["Size"].apply(convert_size)

print(data["Size"].unique())

[1.90e+04 1.40e+04 8.70e+03 2.50e+04 2.80e+03 5.60e+03 2.90e+04 3.30e+04
 3.10e+03 2.80e+04 1.20e+04 2.00e+04 2.10e+04 3.70e+04 2.70e+03 5.50e+03
 1.70e+04 3.90e+04 3.10e+04 4.20e+03 7.00e+03 2.30e+04 6.00e+03 6.10e+03
 4.60e+03 9.20e+03 5.20e+03 1.10e+04 2.40e+04      nan 9.40e+03 1.50e+04
 1.00e+04 1.20e+03 2.60e+04 8.00e+03 7.90e+03 5.60e+04 5.70e+04 3.50e+04
 5.40e+04 2.01e+02 3.60e+03 5.70e+03 8.60e+03 2.40e+03 2.70e+04 2.50e+03
 1.60e+04 3.40e+03 8.90e+03 3.90e+03 2.90e+03 3.80e+04 3.20e+04 5.40e+03
 1.80e+04 1.10e+03 2.20e+03 4.50e+03 9.80e+03 5.20e+04 9.00e+03 6.70e+03
 3.00e+04 2.60e+03 7.10e+03 3.70e+03 2.20e+04 7.40e+03 6.40e+03 3.20e+03
 8.20e+03 9.90e+03 4.90e+03 9.50e+03 5.00e+03 5.90e+03 1.30e+04 7.30e+04
 6.80e+03 3.50e+03 4.00e+03 2.30e+03 7.20e+03 2.10e+03 4.20e+04 7.30e+03
 9.10e+03 5.50e+04 2.30e+01 6.50e+03 1.50e+03 7.50e+03 5.10e+04 4.10e+04
 4.80e+04 8.50e+03 4.60e+04 8.30e+03 4.30e+03 4.70e+03 3.30e+03 4.00e+04
 7.80e+03 8.80e+03 6.60e+03 5.10e+03 6.10e+04 6.60e+04 7.90e+01 8.40e+03
 1.18e+02 4.40e+04 6.95e+02 1.60e+03 6.20e+03 1.80e+01 5.30e+04 1.40e+03
 3.00e+03 5.80e+03 3.80e+03 9.60e+03 4.50e+04 6.30e+04 4.90e+04 7.70e+04
 4.40e+03 4.80e+03 7.00e+04 6.90e+03 9.30e+03 8.10e+03 3.60e+04 8.40e+04
 9.70e+04 2.00e+03 1.90e+03 1.80e+03 5.30e+03 4.70e+04 5.56e+02 5.26e+02
 7.60e+04 7.60e+03 5.90e+04 9.70e+03 7.80e+04 7.20e+04 4.30e+04 7.70e+03
 6.30e+03 3.34e+02 3.40e+04 9.30e+04 6.50e+04 7.90e+04 1.00e+05 5.80e+04
 5.00e+04 6.80e+04 6.40e+04 6.70e+04 6.00e+04 9.40e+04 2.32e+02 9.90e+04
 6.24e+02 9.50e+04 8.50e+00 4.10e+01 2.92e+02 1.10e+01 8.00e+04 1.70e+03
 7.40e+04 6.20e+04 6.90e+04 7.50e+04 9.80e+04 8.50e+04 8.20e+04 9.60e+04
 8.70e+04 7.10e+04 8.60e+04 9.10e+04 8.10e+04 9.20e+04 8.30e+04 8.80e+04
 7.04e+02 8.62e+02 8.99e+02 3.78e+02 2.66e+02 3.75e+02 1.30e+03 9.75e+02
 9.80e+02 4.10e+03 8.90e+04 6.96e+02 5.44e+02 5.25e+02 9.20e+02 7.79e+02
 8.53e+02 7.20e+02 7.13e+02 7.72e+02 3.18e+02 5.80e+01 2.41e+02 1.96e+02
 8.57e+02 5.10e+01 9.53e+02 8.65e+02 2.51e+02 9.30e+02 5.40e+02 3.13e+02
 7.46e+02 2.03e+02 2.60e+01 3.14e+02 2.39e+02 3.71e+02 2.20e+02 7.30e+02
 7.56e+02 9.10e+01 2.93e+02 1.70e+01 7.40e+01 1.40e+01 3.17e+02 7.80e+01
 9.24e+02 9.02e+02 8.18e+02 8.10e+01 9.39e+02 1.69e+02 4.50e+01 4.75e+02
 9.65e+02 9.00e+04 5.45e+02 6.10e+01 2.83e+02 6.55e+02 7.14e+02 9.30e+01
 8.72e+02 1.21e+02 3.22e+02 1.00e+03 9.76e+02 1.72e+02 2.38e+02 5.49e+02
 2.06e+02 9.54e+02 4.44e+02 7.17e+02 2.10e+02 6.09e+02 3.08e+02 7.05e+02
 3.06e+02 9.04e+02 4.73e+02 1.75e+02 3.50e+02 3.83e+02 4.54e+02 4.21e+02
 7.00e+01 8.12e+02 4.42e+02 8.42e+02 4.17e+02 4.12e+02 4.59e+02 4.78e+02
 3.35e+02 7.82e+02 7.21e+02 4.30e+02 4.29e+02 1.92e+02 2.00e+02 4.60e+02
 7.28e+02 4.96e+02 8.16e+02 4.14e+02 5.06e+02 8.87e+02 6.13e+02 2.43e+02
 5.69e+02 7.78e+02 6.83e+02 5.92e+02 3.19e+02 1.86e+02 8.40e+02 6.47e+02
 1.91e+02 3.73e+02 4.37e+02 5.98e+02 7.16e+02 5.85e+02 9.82e+02 2.22e+02
 2.19e+02 5.50e+01 9.48e+02 3.23e+02 6.91e+02 5.11e+02 9.51e+02 9.63e+02
 2.50e+01 5.54e+02 3.51e+02 2.70e+01 8.20e+01 2.08e+02 9.13e+02 5.14e+02
 5.51e+02 2.90e+01 1.03e+02 8.98e+02 7.43e+02 1.16e+02 1.53e+02 2.09e+02
 3.53e+02 4.99e+02 1.73e+02 5.97e+02 8.09e+02 1.22e+02 4.11e+02 4.00e+02
 8.01e+02 7.87e+02 2.37e+02 5.00e+01 6.43e+02 9.86e+02 9.70e+01 5.16e+02
 8.37e+02 7.80e+02 9.61e+02 2.69e+02 2.00e+01 4.98e+02 6.00e+02 7.49e+02
 6.42e+02 8.81e+02 7.20e+01 6.56e+02 6.01e+02 2.21e+02 2.28e+02 1.08e+02
 9.40e+02 1.76e+02 3.30e+01 6.63e+02 3.40e+01 9.42e+02 2.59e+02 1.64e+02
 4.58e+02 2.45e+02 6.29e+02 2.80e+01 2.88e+02 7.75e+02 7.85e+02 6.36e+02
 9.16e+02 9.94e+02 3.09e+02 4.85e+02 9.14e+02 9.03e+02 6.08e+02 5.00e+02
 5.40e+01 5.62e+02 8.47e+02 9.57e+02 6.88e+02 8.11e+02 2.70e+02 4.80e+01
 3.29e+02 5.23e+02 9.21e+02 8.74e+02 9.81e+02 7.84e+02 2.80e+02 2.40e+01
 5.18e+02 7.54e+02 8.92e+02 1.54e+02 8.60e+02 3.64e+02 3.87e+02 6.26e+02
 1.61e+02 8.79e+02 3.90e+01 9.70e+02 1.70e+02 1.41e+02 1.60e+02 1.44e+02
 1.43e+02 1.90e+02 3.76e+02 1.93e+02 2.46e+02 7.30e+01 6.58e+02 9.92e+02
 2.53e+02 4.20e+02 4.04e+02 4.70e+02 2.26e+02 2.40e+02 8.90e+01 2.34e+02
 2.57e+02 8.61e+02 4.67e+02 1.57e+02 4.40e+01 6.76e+02 6.70e+01 5.52e+02
 8.85e+02 1.02e+03 5.82e+02 6.19e+02]

In [29]:
#Sur les données != de Varies with device"
stats_size = data["Size"].describe()
print(stats_size)

count      8831.000000
mean      21287.788303
std       22540.247459
min           8.500000
25%        4700.000000
50%       13000.000000
75%       29000.000000
max      100000.000000
Name: Size, dtype: float64

In [30]:
#Convertir les données en int 
data['Installs'] = data['Installs'].replace({',': '', r'\+': ''}, regex=True)
data['Installs'] = data['Installs'].astype(int)

installs = data['Installs'].unique()
print(installs)

[     10000     500000    5000000   50000000     100000      50000
    1000000   10000000       5000  100000000 1000000000       1000
  500000000         50        100        500         10          1
          5          0]

In [31]:
stats_installs = data["Installs"].describe()
print(stats_installs)

count    1.035700e+04
mean     1.415776e+07
std      8.023955e+07
min      0.000000e+00
25%      1.000000e+03
50%      1.000000e+05
75%      1.000000e+06
max      1.000000e+09
Name: Installs, dtype: float64

In [32]:
data.head(5)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Last Updated
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19000.0,10000,Free,0.0,Everyone,"January 7, 2018"
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14000.0,500000,Free,0.0,Everyone,"January 15, 2018"
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8700.0,5000000,Free,0.0,Everyone,"August 1, 2018"
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25000.0,50000000,Free,0.0,Teen,"June 8, 2018"
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2800.0,100000,Free,0.0,Everyone,"June 20, 2018"

In [33]:
print(data["Content Rating"].unique())

['Everyone' 'Teen' 'Everyone 10+' 'Mature 17+' 'Adults only 18+' 'Unrated']

In [34]:
stats_content_rating = data["Content Rating"].describe()
print(stats_content_rating)

count        10357
unique           6
top       Everyone
freq          8382
Name: Content Rating, dtype: object

In [35]:
content_rating_counts = data["Content Rating"].value_counts()
print(content_rating_counts)

Content Rating
Everyone           8382
Teen               1146
Mature 17+          447
Everyone 10+        377
Adults only 18+       3
Unrated               2
Name: count, dtype: int64

In [36]:
unrated_apps = data[data["Content Rating"] == 'Unrated']
print(unrated_apps)

                         App Category  Rating Reviews    Size  Installs  Type  \
7312     Best CG Photography   FAMILY     NaN       1  2500.0       500  Free
8266  DC Universe Online Map    TOOLS     4.1    1186  6400.0     50000  Free

      Price Content Rating       Last Updated
7312    0.0        Unrated      June 24, 2015
8266    0.0        Unrated  February 27, 2012

In [37]:
#Application de photo pour tout le monde
data.loc[data['App'] == 'Best CG Photography', 'Content Rating'] = 'Everyone'

#Apllication jeu vidéo adapté Teen 
data.loc[data['App'] == 'DC Universe Online Map', 'Content Rating'] = 'Teen'

In [38]:
print(data["Last Updated"].unique())

['January 7, 2018' 'January 15, 2018' 'August 1, 2018' ...
 'January 20, 2014' 'February 16, 2014' 'March 23, 2014']

In [39]:
data['Last Updated'] = pd.to_datetime(data['Last Updated'], errors='coerce')
data['Last Updated'] = data['Last Updated'].dt.year
print(data['Last Updated'].unique())

[2018 2017 2014 2016 2015 2013 2012 2011 2010]

In [40]:
stats_last_updates= data["Last Updated"].describe()
print(stats_last_updates)

count    10357.000000
mean      2017.382929
std          1.112766
min       2010.000000
25%       2017.000000
50%       2018.000000
75%       2018.000000
max       2018.000000
Name: Last Updated, dtype: float64

In [41]:
print(data['Reviews'].unique())

['159' '967' '87510' ... '603' '1195' '398307']

In [42]:
data['Reviews'] = pd.to_numeric(data['Reviews'], errors='coerce')
print(data['Reviews'].unique())

[   159    967  87510 ...    603   1195 398307]

In [43]:
stats_reviews= data["Reviews"].describe()
print(stats_reviews)

count    1.035700e+04
mean     4.059046e+05
std      2.696778e+06
min      0.000000e+00
25%      3.200000e+01
50%      1.680000e+03
75%      4.641600e+04
max      7.815831e+07
Name: Reviews, dtype: float64

In [44]:
data.head(5)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Last Updated
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19000.0,10000,Free,0.0,Everyone,2018
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14000.0,500000,Free,0.0,Everyone,2018
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8700.0,5000000,Free,0.0,Everyone,2018
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25000.0,50000000,Free,0.0,Teen,2018
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2800.0,100000,Free,0.0,Everyone,2018

In [45]:
print(data["Rating"].unique())

[4.1 3.9 4.7 4.5 4.3 4.4 3.8 4.2 4.6 3.2 4.  nan 4.8 4.9 3.6 3.7 3.3 3.4
 3.5 3.1 5.  2.6 3.  1.9 2.5 2.8 2.7 1.  2.9 2.3 2.2 1.7 2.  1.8 2.4 1.6
 2.1 1.4 1.5 1.2]

In [46]:
nan_count = data["Rating"].isna().sum()
print(f"Le nombre de lignes nan dans la colonne 'Rating' est : {nan_count}")

Le nombre de lignes nan dans la colonne 'Rating' est : 1465

Pour combler les données manquantes, je vais : 
- calculer la médiane du rating selon les catégories
- ajouter cette valeur aux lignes manquantes selon les catégories

In [47]:
rating_median_by_category = data.groupby("Category")["Rating"].median()
print(rating_median_by_category )

Category
ART_AND_DESIGN         4.40
AUTO_AND_VEHICLES      4.30
BEAUTY                 4.30
BOOKS_AND_REFERENCE    4.50
BUSINESS               4.25
COMICS                 4.40
COMMUNICATION          4.30
DATING                 4.10
EDUCATION              4.40
ENTERTAINMENT          4.20
EVENTS                 4.50
FAMILY                 4.30
FINANCE                4.30
FOOD_AND_DRINK         4.30
GAME                   4.30
HEALTH_AND_FITNESS     4.50
HOUSE_AND_HOME         4.20
LIBRARIES_AND_DEMO     4.20
LIFESTYLE              4.20
MAPS_AND_NAVIGATION    4.20
MEDICAL                4.30
NEWS_AND_MAGAZINES     4.20
PARENTING              4.40
PERSONALIZATION        4.40
PHOTOGRAPHY            4.30
PRODUCTIVITY           4.30
SHOPPING               4.30
SOCIAL                 4.30
SPORTS                 4.30
TOOLS                  4.20
TRAVEL_AND_LOCAL       4.20
VIDEO_PLAYERS          4.20
WEATHER                4.30
Name: Rating, dtype: float64

In [48]:
data["Rating"] = data.apply(
    lambda row: rating_median_by_category[row["Category"]] if pd.isna(row["Rating"]) else row["Rating"],
    axis=1
)

In [49]:
print(data["Rating"].isna().sum())

0

In [50]:
data.head(10)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Last Updated
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19000.0,10000,Free,0.0,Everyone,2018
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14000.0,500000,Free,0.0,Everyone,2018
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8700.0,5000000,Free,0.0,Everyone,2018
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25000.0,50000000,Free,0.0,Teen,2018
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2800.0,100000,Free,0.0,Everyone,2018
5,Paper flowers instructions,ART_AND_DESIGN,4.4,167,5600.0,50000,Free,0.0,Everyone,2017
6,Smoke Effect Photo Maker - Smoke Editor,ART_AND_DESIGN,3.8,178,19000.0,50000,Free,0.0,Everyone,2018
7,Infinite Painter,ART_AND_DESIGN,4.1,36815,29000.0,1000000,Free,0.0,Everyone,2018
8,Garden Coloring Book,ART_AND_DESIGN,4.4,13791,33000.0,1000000,Free,0.0,Everyone,2017
9,Kids Paint Free - Drawing Fun,ART_AND_DESIGN,4.7,121,3100.0,10000,Free,0.0,Everyone,2018